SERVE_PORT: 5500
TOOL_SERVE_PORT: 5501

DISABLE_SIGNUP: false

JWT_EXP_HOURS: 480

SERCET_KEY: 'octopus'

MYSQL_HOST: "172.23.248.9"
MYSQL_USERNAME: "root"
MYSQL_PASSWORD: "miniso@2019"
MYSQL_DB: "octopus"

TASK_COVER_STORAGE_PATH: 'storage/board-cover'