SERVE_PORT: 5500
TOOL_SERVE_PORT: 5501

DISABLE_SIGNUP: false

JWT_EXP_HOURS: 480

SERCET_KEY: 'octopus'

MYSQL_HOST: "localhost"
MYSQL_USERNAME: "octopuese"
MYSQL_PASSWORD: "my-secret-user-pw"
MYSQL_DB: "octopuese"

TASK_COVER_STORAGE_PATH: 'storage/board-cover'